

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.yonetmenLabel = QtWidgets.QLabel(self.centralwidget)
        self.yonetmenLabel.setGeometry(QtCore.QRect(10, 10, 81, 41))
        self.yonetmenLabel.setObjectName("yonetmenLabel")
        self.yonetmen = QtWidgets.QLineEdit(self.centralwidget)
        self.yonetmen.setGeometry(QtCore.QRect(90, 20, 131, 21))
        self.yonetmen.setObjectName("yonetmen")
        self.ulkeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ulkeLabel.setGeometry(QtCore.QRect(260, 20, 60, 16))
        self.ulkeLabel.setObjectName("ulkeLabel")
        self.ulke = QtWidgets.QComboBox(self.centralwidget)
        self.ulke.setGeometry(QtCore.QRect(320, 10, 131, 26))
        self.ulke.setObjectName("ulke")
        self.ratingLabel = QtWidgets.QLabel(self.centralwidget)
        self.ratingLabel.setGeometry(QtCore.QRect(510, 20, 60, 16))
        self.ratingLabel.setObjectName("ratingLabel")
        self.rating = QtWidgets.QComboBox(self.centralwidget)
        self.rating.setGeometry(QtCore.QRect(570, 10, 171, 26))
        self.rating.setObjectName("rating")
        self.sureLabel = QtWidgets.QLabel(self.centralwidget)
        self.sureLabel.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.sureLabel.setObjectName("sureLabel")
        self.sure = QtWidgets.QSlider(self.centralwidget)
        self.sure.setGeometry(QtCore.QRect(100, 60, 160, 22))
        self.sure.setOrientation(QtCore.Qt.Horizontal)
        self.sure.setObjectName("sure")
        self.ara = QtWidgets.QPushButton(self.centralwidget)
        self.ara.setGeometry(QtCore.QRect(640, 50, 113, 32))
        self.ara.setObjectName("ara")
        self.sonuclar = QtWidgets.QTableView(self.centralwidget)
        self.sonuclar.setGeometry(QtCore.QRect(20, 110, 761, 431))
        self.sonuclar.setObjectName("sonuclar")
        self.sureYaziLabel = QtWidgets.QLabel(self.centralwidget)
        self.sureYaziLabel.setGeometry(QtCore.QRect(310, 60, 31, 16))
        self.sureYaziLabel.setText("")
        self.sureYaziLabel.setObjectName("sureYaziLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 60, 60, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yonetmenLabel.setText(_translate("MainWindow", "Yönetmen"))
        self.ulkeLabel.setText(_translate("MainWindow", "Ülke"))
        self.ratingLabel.setText(_translate("MainWindow", "Rating"))
        self.sureLabel.setText(_translate("MainWindow", "Süre"))
        self.ara.setText(_translate("MainWindow", "Ara"))
        self.label.setText(_translate("MainWindow", "Dakika"))

